blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', blog_view, name='index'),
    path('/<int:pid>', blog_single, name='single'),
    path('/category/<str:cat_name>', blog_view, name='category'),
    path('/tag/<str:tag_name>', blog_view, name='tag'),
    path('/author/<str:author_username>', blog_view, name='author'),
    path('/search/', blog_search, name='search'),
    path('/rss/feed/', LatestPostsFeed()),
    
]    
 

hivasite/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
import debug_toolbar


sitemaps = {
    'static' : StaticViewSitemap,
    'blog' : BlogSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('website.urls')),
    path('blog' , include('blog.urls')),
    path('members/' , include('django.contrib.auth.urls')),
    path('members/' , include('members.urls')),
    path('sitemap.xml', sitemap, {'sitemaps' : sitemaps},
        name = 'django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
   
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

website/urls.py
from django.contrib import admin
from django.urls import path
from website.views import *



app_name = 'website'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_view, name='index'),
    path('about', about_view, name='about'),
    path('contact', contact_view, name='contact'),
    path('newsletter', newsletter_view, name='newsletter'),

]
 

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from sorl.thumbnail import ImageField
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name
           
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    bio = models.TextField()
    profile_pic = models.ImageField(upload_to='author/', default='author/default.jpg')
    x_profile = models.CharField(max_length=255,null=True, blank=True)
    facebook_profile = models.CharField(max_length=255, null=True, blank=True)
    instagram_profile = models.CharField(max_length=255, null=True, blank=True)
    linkedin_profile = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return str(self.user)


class Post(models.Model):
    image = models.ImageField(upload_to='blog/', default='blog/default.JPG')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    tags = TaggableManager()
    category = models.ManyToManyField(Category) 
    counted_view = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    login_required = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
   
    class Meta:
        ordering = ('-created_date',)
    
    def __str__(self):
        return "{}-{}".format(self.title, self.id)
    
    def get_absolute_url(self):
        return reverse('blog:single', kwargs={'pid':self.id})
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ('-created_date',)
    def __str__(self):
        return self.name

website/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ('-created_date',)
    def __str__(self):
        return self.name
    
class Newsletter(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

blog/views.py
from django.shortcuts import render,get_object_or_404
from blog.models import Post, Comment
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib import messages
from blog.forms import CommentForm
from django.urls import reverse
from django.http import HttpResponseRedirect


def blog_view (request,**kwargs):
    posts = Post.objects.filter(status=1)
    if kwargs.get('cat_name') != None:
        posts = posts.filter(category__name=kwargs['cat_name'])
    if kwargs.get('author_username') != None:
        posts = posts.filter(author__username=kwargs['author_username'])
    if kwargs.get('tag_name') != None:
        posts = posts.filter(tags__name__in=kwargs['tag_name']) 
    posts = Paginator(posts,3)
    try:
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)
    context={'posts': posts}
    return render(request,'blog/blog_home.html', context)

def blog_single (request,pid):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request,messages.SUCCESS,'your comment submitted successfully')
        else:
            messages.add_message(request,messages.ERROR,'your comment didnt submitted')

    posts = Post.objects.filter(status=1)
    post = get_object_or_404(posts,pk=pid)
    if not post.login_required:
        comments = Comment.objects.filter(post=post.id, approved=True)
        next = posts.filter(id__gt=post.id).order_by('id').first()
        previous = posts.filter(id__lt=post.id).order_by('-id').first()
        context={'post': post, 'comments':comments, 'next': next, 'previous': previous}
        return render(request,'blog/blog_single.html', context)
    else:
        return render(request,'accounts/signup.html', context)

def blog_category(request,cat_name):
    posts = Post.objects.filter(status=1)
    posts = posts.filter(category__name=cat_name) 
    context={'posts': posts}
    return render(request,'blog/blog_home.html', context)

def blog_search(request):
    posts = Post.objects.filter(status=1)
    if request.method == 'GET':
        if s := request.GET.get('s'):
            posts =posts.filter(content__contains=s)
            
    context={'posts': posts}
    return render(request,'blog/blog_home.html', context)
 

website/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from website.models import Contact, Newsletter
from website.forms import ContactForm, NewsletterForm
from django.contrib import messages

def index_view (request):
    return render(request,'website/index.html')

def about_view (request):
    return render(request,'website/about.html')


def contact_view (request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request,messages.SUCCESS,'your ticket submitted successfully')
        else:
            messages.add_message(request,messages.ERROR,'your ticket didnt submitted')
    form = ContactForm()
    context = {'form':form}
    return render(request,'website/contact.html',context)

def newsletter_view (request):
    if request.method == 'POST':
        form = NewsletterForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/')
    

templates/base.html
{% load static%}
<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Favicon-->
	<link rel="shortcut icon" href="#">
	<!-- Author Meta -->
	<meta name="author" content="colorlib">
	<!-- Meta Description -->
	<meta name="description" content="">
	<!-- Meta Keyword -->
	<meta name="keywords" content="">
	<!-- meta character set -->
	<meta charset="UTF-8">
	<!-- Site Title -->
	<title>HIVA</title>

	<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
	<!--
        CSS
        ============================================= -->
	<link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
	<link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
	<link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body> 
	<header id="header">
		<div class="header-top">
			<div class="container">
				<div class="row align-items-center">
					<div class="col-lg-6 col-sm-6 col-6 header-top-left">
						<ul>
							{% if request.user.is_authenticated %}
							<li><a href="#">Hello {{request.user.username}}</a></li>
							<li><a href="{% url 'logout' %}">Logout</a></li>
							<li><a href="{% url 'password_change' %}">Change Password</a></li>
							{% else %}
							<li><a href="{% url 'login' %}">Login</a></li>
							<li><a href="{% url 'register_user' %}">Signup</a></li>
							{% endif %}
						</ul>
					</div>
					<div class="col-lg-6 col-sm-6 col-6 header-top-right">
						<div class="header-social">
							<a href="https://www.facebook.com/00ArtbySarah00?mibextid=ZbWKwL"><i
									class="fa fa-facebook"></i></a>
							<a href="https://instagram.com/sarah__esm_?utm_source=qr&igshid=MThlNWY1MzQwNA=="><i
									class="fa fa-instagram"></i></a>
							<a href="http://www.linkedin.com/in/sarah-sargol-esmaeili-434222107"><i
									class="fa fa-linkedin"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container main-menu">
			<div class="row align-items-center justify-content-between d-flex">
				<div id="logo">
					<a href="{% url 'website:index' %}"><img src="{% static 'img/logo.png' %}" alt="" title="" /></a>
				</div>
				<nav id="nav-menu-container">
					<ul class="nav-menu">
						<li><a href="{% url 'website:index' %}">Home</a></li>
						<li><a href="{% url 'website:about' %}">About</a></li>
						<li><a href="{% url 'blog:index' %}">Blog</a></li>
						</li>

						<li><a href="{% url 'website:contact' %}">Contact</a></li>
					</ul>
				</nav><!-- #nav-menu-container -->
			</div>
		</div>
	</header><!-- #header -->

	{% block content %}

	{% endblock %}

	<!-- start footer Area -->
	<footer class="footer-area section-gap">
		<div class="container">

			<div class="row">
				<div class="col-lg-3  col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>About Agency</h6>
						<p>
							The world has become so fast paced that people don’t want to stand by reading a page of
							information, they would much rather look at a presentation and understand the message. It
							has come to a point
						</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>Navigation Links</h6>
						<div class="row">
							<div class="col">
								<ul>
									<li><a href="{% url 'website:index' %}">Home</a></li>
									<li><a href="{% url 'blog:index' %}">Blog</a></li>
									<li><a href="https://www.facebook.com/00ArtbySarah00?mibextid=ZbWKwL"><i
												class="fa fa-facebook"></i></a></li>
									<li><a
											href="https://instagram.com/sarah__esm_?utm_source=qr&igshid=MThlNWY1MzQwNA=="><i
												class="fa fa-instagram"></i></a></li>
								</ul>
							</div>
							<div class="col">
								<ul>
									<li><a href="{% url 'website:about' %}">About</a></li>
									<li><a href="{% url 'website:contact' %}">Contact</a></li>
									<li><a href="http://www.linkedin.com/in/sarah-sargol-esmaeili-434222107"><i
												class="fa fa-linkedin"></i></a></li>
									<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-3  col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>Newsletter</h6>
						<p>
							Get the Latest Updates Delivered to Your Inbox.
						</p>
						<div>
							<form action="{% url 'website:newsletter' %}" method="post" class="subscription relative">
								{% csrf_token %}
								<div class="input-group d-flex flex-row">
									<input name="email" placeholder="Email Address" onfocus="this.placeholder = ''"
										onblur="this.placeholder = 'Email Address '" required="" type="email">
									<button type="submit" class="btn bb-btn"><span
											class="lnr lnr-location"></span></button>
								</div>
								<div class="mt-10 info"></div>
							</form>
						</div>
					</div>
				</div>
				<div class="col-lg-3  col-md-6 col-sm-6">
					<div class="single-footer-widget mail-chimp">
						<h6 class="mb-20">InstaFeed</h6>
						<ul class="instafeed d-flex flex-wrap">
							<li><img src="{% static 'img/i1.jpg' %}" alt></li>
							<li><img src="{% static 'img/i2.jpg' %}" alt></li>
							<li><img src="{% static 'img/i3.jpg' %}" alt></li>
							<li><img src="{% static 'img/i4.jpg' %}" alt></li>
							<li><img src="{% static 'img/i5.jpg' %}" alt></li>
							<li><img src="{% static 'img/i6.jpg' %}" alt></li>
							<li><img src="{% static 'img/i7.jpg' %}" alt></li>
							<li><img src="{% static 'img/i8.jpg' %}" alt></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="row footer-bottom d-flex justify-content-between align-items-center">
				<p class="col-lg-8 col-sm-12 footer-text m-0">
				</p>
				
			</div>
		</div>
	</footer>
	<!-- End footer Area -->

	<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
	<script src="{% static 'js/popper.min.js' %}"></script>
	<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery-ui.js' %}"></script>
	<script src="{% static 'js/easing.min.js' %}"></script>
	<script src="{% static 'js/hoverIntent.js' %}"></script>
	<script src="{% static 'js/superfish.min.js' %}"></script>
	<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/mail-script.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/blog/blog_single.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load blog_tags %}
{% block content %}

<!-- start banner Area -->
<section class="relative about-banner">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content col-lg-12">
				<h1 class="text-white">
					{{post.title}}
				</h1>
				<p class="text-white link-nav"><a href="{% url 'website:index' %}">Home </a> <span
						class="lnr lnr-arrow-right"></span><a href="{% url 'blog:index' %}">Blog </a> <span
						class="lnr lnr-arrow-right"></span>{{post.title}}</p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- Start post-content Area -->
<section class="post-content-area single-post-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 posts-list">
				<div class="single-post row">
					<div class="col-lg-12">
						<div class="feature-img">
						<img class="img-fluid" src="{{post.image.url}}" alt="">
						</div>
					</div>
					<div class="col-lg-3  col-md-3 meta-details">
						<ul class="tags">
							{% for cat in post.category.all %}
							    <a href="{% url 'blog:category' cat_name=cat.name %}">{{ cat.name }}</a>{% if not forloop.last %},{% endif %}
							{% endfor %}
						</ul>
						<div class="user-details row">
							<p class="user-name col-lg-12 col-md-12 col-6"><a href="{% url 'blog:author' author_username=post.author.username %}">{{post.author.get_full_name}}</a> <span
									class="lnr lnr-user"></span></p>
							<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.published_date|date:"D d M Y"}}</a> <span
									class="lnr lnr-calendar-full"></span></p>
							<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.counted_view}} Views</a> <span
									class="lnr lnr-eye"></span></p>
							<p class="comments col-lg-12 col-md-12 col-6"><a href="#">{{ comments|length }} comments </a> <span
									class="lnr lnr-bubble"></span></p>
							<ul class="social-links col-lg-12 col-md-12 col-6">
								<li><a href="{{post.author.profile.facebook_profile}}"><i class="fa fa-facebook"></i></a></li>
        						<li><a href="{{post.author.profile.x_profile}}"><i class="fa fa-twitter"></i></a></li>
      							<li><a href="{{post.author.profile.instagram_profile}}"><i class="fa fa-instagram"></i></a></li>
        						<li><a href="{{post.author.profile.linkdin_profile}}"><i class="fa fa-linkedin"></i></a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-9 col-md-9">
						<h3 class="mt-20 mb-20">{{post.title}}</h3>
						<p class="excert">
							{{post.content|safe}}
						</p> 
					</div>
				</div>
				<div class="navigation-area">
					<div class="row">
						{% if previous %}
						<div
							class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
							<div class="thumb">
								<a href="{% url 'blog:single' pid=previous.id %}"><img class="img-fluid" src="{{previous.image.url}}" alt=""></a>
							</div>
							<div class="arrow">
								<a href="{% url 'blog:single' pid=previous.id %}"><span class="lnr text-white lnr-arrow-left"></span></a>
							</div>
							<div class="detials">
								<p>Prev Post</p>
								<a href="{% url 'blog:single' pid=previous.id %}">
									<h4>{{ previous.title }}</h4>
								</a>
							</div>
						</div>
						{% endif %}
						{% if next %}
						<div
							class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
							<div class="detials">
								<p>Next Post</p>
								<a href="{% url 'blog:single' pid=next.id %}">
									<h4>{{ next.title }}</h4>
								</a>
							</div>
							<div class="arrow">
								<a href="{% url 'blog:single' pid=next.id %}"><span class="lnr text-white lnr-arrow-right"></span></a>
							</div>
							<div class="thumb">
								<a href="{% url 'blog:single' pid=next.id %}"><img class="img-fluid" src="{{next.image.url}}" alt=""></a>
							</div>
						</div>
						{% endif %}
					</div>
				</div>
				<div class="comments-area">
					<h4> {{ comments|length }} commens </h4>
					<div class="comment-list">
						{% for comment in comments %}
						<div class="single-comment justify-content-between d-flex">
							<div class="user justify-content-between d-flex">
								<div class="thumb">
									<img src="{% static 'img/blog/c1.png' %}" alt="">
								</div>
								<div class="desc">
									<h5><a href="#">{{ comment.name }}</a></h5>
									<p class="date">{{ comment.created_date|naturalday }} </p>
									<p class="comment">
										{{ comment.message }}
									</p> 
								</div>
							</div>
							<!--
							<div class="reply-btn">
								<a href="" class="btn-reply text-uppercase">reply</a>
							</div>
							-->
						</div>
						{% empty %}
						<p> no comments here be the first one to tell your thoughts </p>
					{% endfor %}
					</div> 
				</div>
				<div class="comment-form">
					<h4>Leave a Comment</h4>
					<form method="post" action="{% url 'blog:single' pid=post.id %}">
						{% csrf_token %}
						<input type="hidden" name="post" value={{post.id}}>
						{% if request.user.is_authenticated %}
						<input type="hidden" name="name" value={{request.user.first_name}}>
						<input type="hidden" name="email" value={{request.user.email}}>
						{% else %}
						<div class="form-group form-inline">
							<div class="form-group col-lg-6 col-md-12 name">
								<input type="text" class="form-control" name="name" placeholder="Enter Name"
									onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
							</div>
							<div class="form-group col-lg-6 col-md-12 email">
								<input type="email" class="form-control" name="email" placeholder="Enter email address"
									onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
							</div>
						</div>
						{% endif %}
						<div class="form-group">
							<input type="text" class="form-control" name="subject" placeholder="Subject"
								onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">
						</div>
						<div class="form-group">
							<textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege"
								onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'"
								required=""></textarea>
						</div>
						<button type="submit" class="primary-btn text-uppercase">Post Comment</a>
					</form> 
				</div>
			{% if messages %}
			{% for message in messages %}
				<div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
			{% endfor %}
			{% endif %}
			{% if form.errors %}
			<div class="alert alert-error">
				<h4>Please fix the following errors</h4>
				<ul>
					{% for field in form %}
					    {% if field.errors %}
						    {% for error in field.errors %}
							    <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
							{% endfor %}
						{% endif %}
					{% endfor %}
				</ul>
					{% if form.non_field_errors %}
						{{ form.non_field_errors }}
					{% endif %}
			</div>
			{% endif %}
			</div>
			<div class="col-lg-4 sidebar-widgets">
				<div class="widget-wrap">
					
					{% include 'blog/blog_search.html' %}

					{% include 'blog/blog_writer.html' %}

					{% include 'blog/blog_tags.html' %}

					{% latestposts %}

					{% include 'blog/blog_newsletter.html' %}

					{% include 'blog/blog_ads.html' %}
					
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End post-content Area -->

{% endblock %}

templates/website/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- start banner Area -->
<section class="relative about-banner">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content col-lg-12">
				<h1 class="text-white">
					Contact Us
				</h1>
				<p class="text-white link-nav"><a href="{% url 'website:index' %}">Home </a> <span class="lnr lnr-arrow-right"></span>
					<a href="contact.html"> Contact Us</a></p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- Start contact-page Area -->
<section class="contact-page-area section-gap">
	<div class="container">
		<div class="row">
			<div class="map-wrap" style="width:100%; height: 445px;" id="map">
				<iframe src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d3870.659790047793!2d121.1578326818606!3d14.038169457153888!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1s339%20luta%20del%20norte%20malvar%20batangas!5e0!3m2!1sen!2sph!4v1699354580929!5m2!1sen!2sph" 
				width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
			</div>
			<div class="col-lg-4 d-flex flex-column address-wrap">
				<div class="single-contact-address d-flex flex-row">
					<div class="icon">
						<span class="lnr lnr-home"></span>
					</div>
					<div class="contact-details">
						<h5>Malvar, Batangas, Philippine</h5>
						<p>
							339 Luta Del Norte
						</p>
					</div>
				</div>
				<div class="single-contact-address d-flex flex-row">
					<div class="icon">
						<span class="lnr lnr-phone-handset"></span>
					</div>
					<div class="contact-details">
						<h5>00 (63) 919 996 0450</h5>
						<p>Mon to Fri 9am to 6 pm</p>
					</div>
				</div>
				<div class="single-contact-address d-flex flex-row">
					<div class="icon">
						<span class="lnr lnr-envelope"></span>
					</div>
					<div class="contact-details">
						<h5>hiva.trading2023@gmail.com</h5>
						<p>Send us your query anytime!</p>
					</div>
				</div>
			</div>
			<div class="col-lg-8">
				<form class="form-area contact-form text-right"  action="{% url 'website:contact' %}" method="post">
					<div class="row">
						{% csrf_token %}
						<div class="col-lg-6 form-group">
							<input name="name" placeholder="Enter your name" onfocus="this.placeholder = ''"
								onblur="this.placeholder = 'Enter your name'" class="common-input mb-20 form-control"
								required="" type="text">

							<input name="email" placeholder="Enter email address"
								pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$"
								onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'"
								class="common-input mb-20 form-control" required="" type="email">

							<input name="subject" placeholder="Enter subject" onfocus="this.placeholder = ''"
								onblur="this.placeholder = 'Enter subject'" class="common-input mb-20 form-control"
								required="" type="text">
						</div>
						<div class="col-lg-6 form-group">
							<textarea class="common-textarea form-control" name="message" placeholder="Enter Messege"
								onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Messege'"
								required=""></textarea>
						</div>
						<div class="col-lg-12">
							<div class="pb-3">
								{{ form.captcha }}
							</div>
						<div class="alert-msg" style="text-align: left;"></div>
						<button type="submit" class="genric-btn primary" style="float: right;">Send Message</button>
						</div>
					</div>
				</form>
			</div>
			{% if messages %}
			{% for message in messages %}
				<div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
			{% endfor %}
			{% endif %}
			{% if form.errors %}
			<div class="alert alert-error">
				<h4>Please fix the following errors</h4>
				<ul>
					{% for field in form %}
					    {% if field.errors %}
						    {% for error in field.errors %}
							    <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
							{% endfor %}
						{% endif %}
					{% endfor %}
				</ul>
					{% if form.non_field_errors %}
						{{ form.non_field_errors }}
					{% endif %}
			</div>
			{% endif %}
		</div>
	</div>
</section>
<!-- End contact-page Area -->

{% endblock %}